apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nodes-reader-clusterrolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: seung
  namespace: default
roleRef: 
  kind: ClusterRole
  name: node-reader
  apiGroup: rbac.authorization.k8s.io
