apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: login
  template:
    metadata:
      name: 
      labels: 
        app: login
    spec:
      containers:
      - name: login-api-server
        image: sjoh0704/django-msa:all
        command: ['python3']
        args: ['MSA-django/backend/manage.py', 'runserver', '0.0.0.0:5000']
        ports:
        - containerPort: 5000
  
